# Generated by Django 3.0.2 on 2020-02-09 09:49

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import umiam.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement_name', models.CharField(max_length=256)),
                ('achievement_description', models.CharField(blank=True, max_length=1024)),
                ('achievement_pic', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=256)),
                ('event_description', models.CharField(blank=True, max_length=1024)),
                ('event_pic', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='HMC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='QuickLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='HMCMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(upload_to='')),
                ('designation', models.CharField(choices=[('General Secretary', 'General Secretary'), ('Welfare Secretary', 'Welfare Secretary'), ('Mess Convener', 'Mess Convener'), ('Cultural Secretary', 'Cultural Secretary'), ('Literary Secretary', 'Literary Secretary'), ('Technical Secretary', 'Technical Secretary'), ('Sports Secretary', 'Sports Secretary'), ('Maintenance Secretary', 'Maintenance Secretary'), ('Warden', 'Warden'), ('Associate Warden', 'Associate Warden'), ('Caretaker', 'Caretaker')], max_length=50)),
                ('iitg_email', models.EmailField(max_length=254, validators=[umiam.models.is_iitg_email])),
                ('phone_number', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('hmc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='umiam.HMC')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
