# Generated by Django 3.0.2 on 2020-02-09 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umiam', '0002_auto_20200209_1048'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryOverview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=256)),
                ('event_description', models.CharField(blank=True, max_length=1024)),
                ('event_pic', models.ImageField(upload_to='')),
            ],
        ),
    ]
