# Generated by Django 3.0.2 on 2020-02-09 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umiam', '0003_galleryoverview'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_name', models.CharField(max_length=64)),
                ('details', models.CharField(blank=True, max_length=1024)),
                ('pic', models.ImageField(upload_to='')),
            ],
        ),
    ]
