# Generated by Django 3.0.3 on 2020-02-10 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umiam', '0004_facility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='achievement_description',
            field=models.TextField(blank=True),
        ),
    ]
