# Generated by Django 3.0.3 on 2020-02-10 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umiam', '0006_auto_20200210_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='achievement_description',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
